weights: yolov5s.pt
resume: false
data: data/X_shape_detection_1_classes.yaml
epochs: 300
imgsz: 640
cfg: ''
hyp: data/hyps/hyp.scratch.yaml
batch_size: 32
rect: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 10
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp30
